# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ARCHEOSTICKERS
tagline:          'Archeologia e arte distillate in sticker'
description:      'Le archeostickers sono un pacchetto di stickers per Telegram e un riuso di immagini libere tratte da Wikipedia. Le archeostickers sono state ideate e realizzate da opensensorsdata in collaborazione con Professione Archeologo e ArcheoPop per promuovere e riusare i dati liberi di arte e archeologia'
url:              
baseurl:          /
logo:             'lewis_chessmen_logo.svg'
google-analytics-ua: UA-62992830-2
locale:           it-IT


author:
  name:           'archeostickers crew'
  url:            https://twitter.com/archeostickers
  twitter:        'archeostickers'
  facebook:
  facebook-id:    '1151787705' #find your fb-id with http://findmyfbid.com/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/archeostickers/archeostickers.github.io

social:
  twitter:      https://twitter.com/archeostickers
  telegram:     https://telegram.me/addstickers/archeo